config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :create, :edit, :show, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  get 'about', to: 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true ,length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book


  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, length: {minimum:2 ,maximum:20} ,uniqueness: true
  validates :introduction, length: {maximum:50}
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top ,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer
  end
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @books = Book.all
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  # 投稿データの保存
  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@new_book)
    else
      @books = Book.all
      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])  # Bookを取得
    unless book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @user = User.all
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "profile was successfully updated."
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name ,:introduction, :profile_image)
  end


  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
      <h2>User info</h2>
        <%=image_tag user.get_profile_image(100,100)%>
        <table class ="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class= "row">
          <%= link_to edit_user_path(user), class: "btn btn-lg btn-block custom-btn mt-2" do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        </div>
        <% if @new_book.errors.any? %>
          <%= @new_book.errors.count %>error prohibited this book from being saved:
          <ul>
            <% @new_book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      <%= form_with model: new_book, url: books_path, method: :post do |f| %>
        <h2>New book</h2>
        <h5>Title</h5>
        <%= f.text_field :title %>

        <h5>opinion</h5>
        <%= f.text_area :body %>

        <br>
        <%= f.submit 'Create Book' ,class: "btn btn-success" %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class= "container ">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>

    <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_with model: @book do |f| %>
      <%= f.label :title, "Title" %>
      <%= f.text_field :title , value: @book.title ,class: "form-control" %>
      
      <%= f.label :body, "Opinion" %>
      <%= f.text_area :body ,class: "form-control"%>
      <br>
      <%= f.submit 'Update Book', class: "btn btn-secondary" %>
      <br>
      <%= link_to "Show", book_path(@book.id) %> |
      <%= link_to "Back", books_path %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<%= flash[:notice] %>
<div class= "container px-5 px-sm-0">
  <div class= "row">
    <%= render 'list', new_book: @new_book, user: current_user%>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to image_tag(book.user.get_profile_image(100, 100)), user_path(book.user) %>
              </td>
              <td><%=link_to book.title ,book_path(book) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorite_path(book), method: :delete do %>
                      <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorite_path(book), method: :post do %>
                      <i class="fa-regular fa-heart"></i><%= book.favorites.count %> 
                    <% end %>
                  </p>
              <% end %>
              </td>
              <td><p>コメント件数：<%= book.book_comments.count %></p></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class= "container px-5 px-sm-0">
  <div class= "row">
    <%= render 'list', new_book: @new_book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
        </thead>
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                  <%= image_tag(@book.user.get_profile_image(100, 100)) %><br>
                  <span class="user-name"><%= @book.user.name %></span>
                <% end %>
              </td>
              <td><%=link_to @book.title , book_path(@book) %></td>
              <td><%= @book.body %></td>
              <% if @book.user_id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %></td>
                <td><%= link_to "Destroy", book_path(@book),method: :delete, class: "btn btn-danger" %></td>
              <% end %>
              <td>
                  <% if @book.favorited_by?(current_user) %>
                    <p>
                      <%= link_to book_favorite_path(@book), method: :delete do %>
                        <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
                      <% end %>
                    </p>
                  <% else %>
                    <p>
                      <%= link_to book_favorite_path(@book), method: :post do %>
                        <i class="fa-regular fa-heart"></i><%= @book.favorites.count %> 
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <td><p>コメント件数：<%= @book.book_comments.count %></p></td>
            </tr>
        </tbody>
      </table>
      <table class="table table-hover table-inverse">
        <thead>
        </thead>
        <tbody>
          <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td><%= image_tag book_comment.user.get_profile_image(100,100) %></td>
              <td><%= book_comment.comment %></td>
              <td><%= book_comment.user.name %></td>
              <td>
                <% if book_comment.user == current_user %>
                 <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete,  class: "btn btn-danger" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= form_with model: [@book, @book_comment] do |f| %>
        <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" ,class: "form-control" %>
        <%= f.submit "送信" %>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class = "container">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>welcome to <i class="fa-solid fa-book"></i> Bookers!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class = "container">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>welcome to<i class="fa-solid fa-book"></i>Bookers!!</h1>
    <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions

    <br>about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-primary form-control" %>
      </div>
      <br>
      <div class="row">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success form-control" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f46697495f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              
                <%= link_to user_path(current_user.id), class: 'nav-link text-dark' do%>
                  <i class="fa-solid fa-house"></i> Home
                <%end%>
              
                <%= link_to users_path, class: 'nav-link text-dark' do %>
                  <i class="fa-solid fa-users"></i>Users
                <%end%>
                
              
                <%= link_to books_path,class: 'nav-link text-dark' do %>
                  <i class="fa-solid fa-book-open"></i> Books
                <%end%>
              
                <%= link_to  destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do%>
                  <i class="fa-solid fa-right-from-bracket"></i> Log out
                <%end%>
            <% else %>
              
                <%= link_to root_path, class: 'nav-link text-dark' do %>
                  <i class="fa-solid fa-house"></i> Home
                <% end %>
              
                <%= link_to about_path, class: 'nav-link text-dark' do %>
                  <i class="fa-solid fa-link"></i> About
                <% end %>
              
                <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                  <i class="fa-solid fa-user-plus"></i> Sign up
                <% end %>
             
                <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
                  <i class="fa-solid fa-right-to-bracket"></i> Log in
                <% end %>
            <%end%>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <main>
     
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class= "container ">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <% if @user.errors.any? %>
      <%= @user.errors.count %>error prohibited this book from being saved:
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <h2>User info</h2>
    <%= form_with model: @user, local: true do |f| %>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name ,class: "form-control" %>

      <%= f.file_field :profile_image, accept: "image/*", class: "w-100" %>
      
      <%= f.label :introduction, "Introduction" %>
      <%= f.text_field :introduction ,class: "form-control" %>

      <%= f.submit 'Update User', class: "btn btn-secondary" %>
      
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class= "container px-5 px-sm-0">
  <div class= "row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%=image_tag current_user.get_profile_image(100,100)%>
      <table class ="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class= "row">
        <%= link_to edit_user_path(current_user), class: "btn btn-lg btn-block custom-btn mt-2" do %>
          <i class="fa-solid fa-user-gear"></i>
        <% end %>
      </div>

      <%= form_with model: @new_book, url: books_path, method: :post do |f| %>
        <h2>New book</h2>
        <h5>Title</h5>
        <%= f.text_field :title %>

        <h5>opinion</h5>
        <%= f.text_area :body %>

        <br>
        <%= f.submit 'Create Book',class: "btn btn-success"  %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
              
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
          <% @user.each do |user| %>
            <tr>
              <td>
                <%=image_tag user.get_profile_image(80,80)%><br>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show" , user_path(user)%></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class= "container px-5 px-sm-0">
  <div class= "row">
    <div class= "col-md-3">
      <h2>User info</h2>
        <%=image_tag @user.get_profile_image(100,100)%>
        <table class ="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class= "row">
          <%= link_to edit_user_path(@user), class: "btn btn-lg btn-block custom-btn mt-2" do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        </div>

      <%= form_with model: @new_book, url: books_path, method: :post do |f| %>
        <h2>New book</h2>
        <h5>Title</h5>
        <%= f.text_field :title %>

        <h5>opinion</h5>
        <%= f.text_area :body %>

        <br>
        <%= f.submit 'Create Book', class: "btn btn-success" %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books@show</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag(book.user.get_profile_image(100, 100)) %>
                <% end %>
              </td>
              <td><%=link_to book.title ,book_path(book) %></td>
              <td><%= book.body %></td>
              <td>
                  <% if book.favorited_by?(current_user) %>
                    <p>
                      <%= link_to book_favorite_path(book), method: :delete do %>
                        <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                      <% end %>
                    </p>
                  <% else %>
                    <p>
                      <%= link_to book_favorite_path(book), method: :post do %>
                        <i class="fa-regular fa-heart"></i><%= book.favorites.count %> 
                      <% end %>
                    </p>
                  <% end %>
              </td>
              <td><p>コメント件数：<%= book.book_comments.count %></p></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>